# Generated by Django 5.0.7 on 2024-07-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='frame_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='frame_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='frame_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paint_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paint_type_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paint_type_uz',
        ),
    ]
