# Generated by Django 5.0.7 on 2024-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_category_name_en_remove_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=200, null=True, verbose_name='tavsifi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(max_length=200, null=True, verbose_name='tavsifi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(max_length=200, null=True, verbose_name='tavsifi'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_en',
            field=models.CharField(max_length=100, null=True, verbose_name='ramkasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='ramkasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='ramkasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Materiali'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Materiali'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Materiali'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='paint_type_en',
            field=models.CharField(max_length=250, null=True, verbose_name="Bo'yoq turi"),
        ),
        migrations.AddField(
            model_name='product',
            name='paint_type_ru',
            field=models.CharField(max_length=250, null=True, verbose_name="Bo'yoq turi"),
        ),
        migrations.AddField(
            model_name='product',
            name='paint_type_uz',
            field=models.CharField(max_length=250, null=True, verbose_name="Bo'yoq turi"),
        ),
    ]
